image: node:14

cache:
  paths:
    - node_modules/
    - .yarn

stages:
    - build
build:
    stage: build
    script:
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
