image: node:14

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building..."
    - yarn
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build

pages:
  stage: deploy
  script:
    - echo "Deploying..."
    - yarn
    - yarn deploy
    - echo "Deployment Completed..."
  only:
    - master
